# ===============================
# ⚙️ SPRING CONFIG
# ===============================
spring.application.name=AURUS-SERVICE
spring.main.banner-mode=off
spring.jackson.serialization.INDENT_OUTPUT=true

# ===============================
# 🌐 SERVER CONFIG
# ===============================
server.port=1111

# ===============================
# 🧭 EUREKA CONFIG
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ===============================
# 🔐 SSH CONFIGURATION
# ===============================
ssh.jump.host=uat42.auruspay.com
ssh.jump.port=22
ssh.jump.user=vchavan
ssh.jump.pass=Sh!rd!$3_2k26!

ssh.target.user=vchavan
ssh.target.pass=T!rup@t!_2k26!

ssh.timeout.connection=10000
ssh.timeout.command=15000

# ===============================
# 📂 LOG FILE CONFIG
# ===============================
log.base-path=/opt/auruspay_switch/log/auruspay
log.file-name=auruspay.log

# ===============================
# 📊 FILE OUTPUT CONFIG
# ===============================
file.output.path=C:/logs/txn-output

# ===============================
# 📝 LOGGING CONFIG
# ===============================
logging.level.root=INFO
logging.level.com.auruspay=DEBUG
logging.file.name=logs/application.log